import "../styles/globals.css";
import type { AppProps } from "next/app";

import { ChakraProvider, extendTheme } from "@chakra-ui/react";
import Head from "next/head";
import Navbar from "@components/Navbar";
import { TronProvider } from "@components/TronProvider";

const theme = extendTheme({
  styles: {
    global: {
      "html,body": {
        backgroundColor: "black",
      },
      "*": {
        fontFamily: "Poppins",
        color: "white",
        backgroundColor: "transparent",
      },
      a: {
        _hover: {
          textDecoration: "underline",
        },
      },
      button: {
        backgroundColor: "transparent !important",
        border: "1px solid gray",
        _hover: {
          border: "1px solid lightgray",
        },
      },
    },
  },
});

export default function App({ Component, pageProps, router }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <TronProvider>
        <Head>
          <title>Journey: TRON-Native Quests</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Component {...pageProps} key={router.route} />
      </TronProvider>
    </ChakraProvider>
  );
}
